export const RECORD_FACTIONS_DATA_TO_STORE = 'RECORD_FACTIONS_DATA_TO_STORE';
export const REQUEST_FACTIONS_ERROR = 'REQUEST_FACTIONS_ERROR';
export const RECORD_SOLAR_SYSTEM_NAME_TO_STORE =
  'RECORD_SOLAR_SYSTEM_NAME_TO_STORE';
export const REQUEST_SOLAR_SYSTEM_NAME_ERROR =
  'REQUEST_SOLAR_SYSTEM_NAME_ERROR';
export const RECORD_CORPORATION_DATA_TO_STORE =
  'RECORD_CORPORATION_DATA_TO_STORE';
export const REQUEST_CORPORATION_DATA_ERROR = 'REQUEST_CORPORATION_DATA_ERROR';
